export const FETCH_SCHEDULE = "FETCH_SCHEDULE"
export const ADD_MASTER_TO_CELL = "ADD_MASTER_TO_CELL"
export const CHANGE_FIRST_DAY = "CHANGE_FIRST_DAY"
export const CHANGE_LAST_DAY = "CHANGE_LAST_DAY"

export const DECLINE_REC = "DECLINE_REC"
export const DECLINE_REC_BY_DATE_TIME = "DECLINE_REC_BY_DATE_TIME"
export const USER_ASSIGN = "USER_ASSIGN"
export const ADD_MASTER_TO_CELL_MASTER = "ADD_MASTER_TO_CELL_MASTER"
